### PR TITLE
fixed build issues on linux mint

### PR DESCRIPTION
**Pull request by nightflyza**
yep, c99 and implicit include of getopt fixes some build errors

### CODE REVIEW

**Comment by john-sevsk** [comment]
Hi, nightflyza.
It seems you are using some outdated version of compiler.
Accoding to man 3 getopt and [IEEE Std 1003.1](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/unistd.h.html) getopt, optarg, and optopt must be declared in unistd.h. No need to include getopt.h.
-std=c99 flag is also not needed because [gcc](https://gcc.gnu.org/onlinedocs/gcc/Standards.html#Standards) and other compilers already use newer versions of the c standard by default.
Just tried in Linux Mint 18.3 Sylvia x64 with build-essential and libusb-1.0-0-dev packages installed. Build was succesful without any problems. gcc version 5.4.0, clang version 3.8.0.
Which versions do you use? Try to update your software.

**Comment by nightflyza** [comment]
Linux mint 17.2, yep its long term support release (LTS), supported until April 2019.
gcc version 4.8.4 & libusb-1.0-0-dev. Nothing to update.

**Comment by john-sevsk** [comment]
Try this:
`CC="gcc -std=gnu11" make`

**Comment by nightflyza** [comment]
Yep, with gnu11 it works fine as is. 

```
nightfly@badass ~/ttt/cynpro $  CC="gcc -std=gnu11" make
gcc -std=gnu11 -I/usr/include/libusb-1.0   -Wall    cynpro.c  -lusb-1.0   -o cynpro
nightfly@badass ~/ttt/cynpro $ ls -la cynpro
-rwxr-xr-x 1 nightfly nightfly 12866 тра 21 10:02 cynpro
nightfly@badass ~/ttt/cynpro $ 
```

**Pull request closed without merging**
